// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:t2_mobile_application/features/auth/data/models/user_model.dart';
import 'package:t2_mobile_application/features/settings/data/models/settings_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(SettingsModelAdapter());
    registerAdapter(UserModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(SettingsModelAdapter());
    registerAdapter(UserModelAdapter());
  }
}
